# This rule is not used by the project eck-custom-resources itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the es.eck.github.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: eck-custom-resources
    app.kubernetes.io/managed-by: kustomize
  name: es.eck-index-editor-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - indices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - indices/status
  verbs:
  - get
