apiVersion: es.eck.github.com/v1alpha1
kind: IndexTemplate
metadata:
  labels:
    app.kubernetes.io/name: eck-custom-resources
    app.kubernetes.io/managed-by: kustomize
  name: indextemplate-sample
spec:
  # TODO(user): Add fields here
