# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/es.eck.github.com_indices.yaml
- bases/es.eck.github.com_indextemplates.yaml
- bases/config.github.com_projectconfigs.yaml
- bases/es.eck.github.com_indexlifecyclepolicies.yaml
- bases/es.eck.github.com_snapshotlifecyclepolicies.yaml
- bases/es.eck.github.com_ingestpipelines.yaml
- bases/es.eck.github.com_snapshotrepositories.yaml
- bases/kibana.eck.github.com_savedsearches.yaml
- bases/kibana.eck.github.com_indexpatterns.yaml
- bases/kibana.eck.github.com_visualizations.yaml
- bases/kibana.eck.github.com_dashboards.yaml
- bases/es.eck.github.com_elasticsearchroles.yaml
- bases/es.eck.github.com_elasticsearchusers.yaml
- bases/es.eck.github.com_elasticsearchapikeys.yaml
- bases/kibana.eck.github.com_spaces.yaml
- bases/kibana.eck.github.com_lens.yaml
- bases/kibana.eck.github.com_dataviews.yaml
- bases/kibana.eck.github.com_kibanainstances.yaml
- bases/es.eck.github.com_elasticsearchinstances.yaml
- bases/es.eck.github.com_componenttemplates.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
